require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SubscribersController do

  # This should return the minimal set of attributes required to create a valid
  # Subscriber. As you add validations to Subscriber, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all subscribers as @subscribers" do
      subscriber = Subscriber.create! valid_attributes
      get :index
      assigns(:subscribers).should eq([subscriber])
    end
  end

  describe "GET show" do
    it "assigns the requested subscriber as @subscriber" do
      subscriber = Subscriber.create! valid_attributes
      get :show, :id => subscriber.id.to_s
      assigns(:subscriber).should eq(subscriber)
    end
  end

  describe "GET new" do
    it "assigns a new subscriber as @subscriber" do
      get :new
      assigns(:subscriber).should be_a_new(Subscriber)
    end
  end

  describe "GET edit" do
    it "assigns the requested subscriber as @subscriber" do
      subscriber = Subscriber.create! valid_attributes
      get :edit, :id => subscriber.id.to_s
      assigns(:subscriber).should eq(subscriber)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Subscriber" do
        expect {
          post :create, :subscriber => valid_attributes
        }.to change(Subscriber, :count).by(1)
      end

      it "assigns a newly created subscriber as @subscriber" do
        post :create, :subscriber => valid_attributes
        assigns(:subscriber).should be_a(Subscriber)
        assigns(:subscriber).should be_persisted
      end

      it "redirects to the created subscriber" do
        post :create, :subscriber => valid_attributes
        response.should redirect_to(Subscriber.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved subscriber as @subscriber" do
        # Trigger the behavior that occurs when invalid params are submitted
        Subscriber.any_instance.stub(:save).and_return(false)
        post :create, :subscriber => {}
        assigns(:subscriber).should be_a_new(Subscriber)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Subscriber.any_instance.stub(:save).and_return(false)
        post :create, :subscriber => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested subscriber" do
        subscriber = Subscriber.create! valid_attributes
        # Assuming there are no other subscribers in the database, this
        # specifies that the Subscriber created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Subscriber.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => subscriber.id, :subscriber => {'these' => 'params'}
      end

      it "assigns the requested subscriber as @subscriber" do
        subscriber = Subscriber.create! valid_attributes
        put :update, :id => subscriber.id, :subscriber => valid_attributes
        assigns(:subscriber).should eq(subscriber)
      end

      it "redirects to the subscriber" do
        subscriber = Subscriber.create! valid_attributes
        put :update, :id => subscriber.id, :subscriber => valid_attributes
        response.should redirect_to(subscriber)
      end
    end

    describe "with invalid params" do
      it "assigns the subscriber as @subscriber" do
        subscriber = Subscriber.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Subscriber.any_instance.stub(:save).and_return(false)
        put :update, :id => subscriber.id.to_s, :subscriber => {}
        assigns(:subscriber).should eq(subscriber)
      end

      it "re-renders the 'edit' template" do
        subscriber = Subscriber.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Subscriber.any_instance.stub(:save).and_return(false)
        put :update, :id => subscriber.id.to_s, :subscriber => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested subscriber" do
      subscriber = Subscriber.create! valid_attributes
      expect {
        delete :destroy, :id => subscriber.id.to_s
      }.to change(Subscriber, :count).by(-1)
    end

    it "redirects to the subscribers list" do
      subscriber = Subscriber.create! valid_attributes
      delete :destroy, :id => subscriber.id.to_s
      response.should redirect_to(subscribers_url)
    end
  end

end
